apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smart-todo
data:
  SERVER_PORT: "8080"
  BASE_URL: "http://localhost:8080"
  FRONTEND_URL: "http://localhost:3000"
  REDIS_URL: "redis://redis:6379/0"
