apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-todo

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - worker-deployment.yaml
  - migration-job.yaml
  - deployment.yaml
  - service.yaml
